# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='filename',
            field=models.CharField(default='null_filename.txt', max_length=200),
            preserve_default=False,
        ),
    ]
