# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_upload_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='filename',
        ),
    ]
