# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_remove_upload_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='forecastmethod',
            field=models.CharField(choices=[('ann', 'neural network'), ('svm', 'support vector machine'), ('mps', 'multiple proportion smoothing method')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='forecastperiod',
            field=models.CharField(choices=[('s', 'short term'), ('m', 'medium term'), ('l', 'long term')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
