# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import forecast.models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_auto_20170426_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='uploadName',
            field=models.CharField(default=1, max_length=100, verbose_name=forecast.models.user_file_name),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='forecastmethod',
            field=models.CharField(choices=[('ann', 'neural network'), ('svm', 'support vector machine'), ('mps', 'multiple proportion smoothing method')], default='ann', max_length=3, verbose_name='Forecasting method'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='forecastperiod',
            field=models.CharField(choices=[('s', 'short term'), ('m', 'medium term'), ('l', 'long term')], default='m', max_length=1, verbose_name='Forecasting period'),
        ),
    ]
