# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_auto_20170511_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='firstDay',
            field=models.CharField(default='2014/10/20', max_length=20, verbose_name='First Day for forecasting (example:2014/10/20)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='uploadName',
            field=models.CharField(max_length=100, verbose_name='Upload File Name'),
        ),
    ]
